Repository modin-project/modin, pull requests merged in 2018-07, with the labels that each got.

#19 Performance boost in _blocks_to_col by np.concatenate
  modin/pandas/utils.py
Labels: Performance 🚀

#23 Make classes inherit from object
  modin/pandas/indexing.py
  modin/pandas/utils.py
Labels: Python 2 Compatibility

#25 Adding contribution templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#16 Improve groupby performance while keeping API compatibility
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
Labels: Performance 🚀

#26 Adding reproducible benchmarks
  .gitignore
  benchmarks/.gitignore
  benchmarks/arithmetic_benchmark.py
  benchmarks/df_op_benchmark.py
  benchmarks/generate_data.py
  benchmarks/groupby_benchmark.py
  benchmarks/io_benchmark.py
  benchmarks/join_merge_benchmark.py
  benchmarks/pandas/arithmetic_benchmark.py
  benchmarks/pandas/df_op_benchmark.py
  benchmarks/pandas/groupby_benchmark.py
  benchmarks/pandas/io_benchmark.py
  benchmarks/pandas/join_merge_benchmark.py
  benchmarks/pandas/run_pandas_benchmark.py
  benchmarks/pandas/utils.py
  benchmarks/run_benchmark.py
  benchmarks/utils.py
Labels: Benchmarking

#39 Head tail performance
  modin/pandas/dataframe.py
Labels: Performance 🚀

#41 Improve __repr__ performance
  modin/pandas/dataframe.py
  modin/pandas/test/test_dataframe.py
Labels: Performance 🚀

#47 Implement post task gc hook
  modin/pandas/groupby.py
  modin/pandas/utils.py
Labels: Performance 🚀

#51 Fix bug where fillna assumes each column is its own partition
  modin/pandas/dataframe.py
Labels: bug :bug:

#49 Automatically determining number of partitions based on cores
  modin/pandas/__init__.py
Labels: Performance 🚀
