Repository modin-project/modin, pull requests merged in 2018-10, with the labels that each got.

#114 Fix repr(df.T) performance
  modin/data_management/data_manager.py
Labels: Performance 🚀

#121 Fixed empty series return value
  modin/data_management/data_manager.py
Labels: bugs and bugfixes :bomb:

#127 Fixed cumulative functions
  modin/pandas/dataframe.py
Labels: bugs and bugfixes :bomb:

#129 Fixed mean
  modin/data_management/data_manager.py
  modin/pandas/dataframe.py
Labels: bugs and bugfixes :bomb:

#133 Fix numeric functions
  modin/data_management/data_manager.py
  modin/pandas/dataframe.py
Labels: bugs and bugfixes :bomb:

#119 Fix issue where empty partitions caused incorrect behavior
  modin/data_management/partitioning/partition_collections.py
Labels: bugs and bugfixes :bomb:

#139 Adding black check to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation :bookmark_tabs:

#125 Fix `bool_only` argument functions
  modin/data_management/data_manager.py
  modin/pandas/dataframe.py
Labels: bugs and bugfixes :bomb:

#135 Fix mode
  modin/data_management/data_manager.py
Labels: bugs and bugfixes :bomb:

#106 Documentation update
  docs/architecture.rst
  docs/contact.rst
  docs/contributing.rst
  docs/img/block_partitions_diagram.png
  docs/img/modin_architecture_diagram.png
  docs/index.rst
  docs/installation.rst
  docs/pandas_on_ray.rst
  docs/pandas_supported.rst
  docs/sql_on_ray.rst
  docs/troubleshooting.rst
  docs/using_modin.rst
Labels: documentation :bookmark_tabs:
