Repository modin-project/modin, pull requests merged in 2020-12, with the labels that each got.

#2331 TEST-#2290: Cover by tests General Parsing Configuration parameters of read_csv
  modin/pandas/test/test_io.py
  modin/pandas/test/utils.py
Labels: Ready for review

#2454 FIX-#2453: Remove sorting indices for equal values in `Series.value_counts`
  docs/supported_apis/series_supported.rst
  docs/supported_apis/utilities_supported.rst
  modin/backends/pandas/query_compiler.py
  modin/pandas/test/test_general.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#2477 TEST-#2294: Cover by tests Iteration parameters of read_csv
  modin/pandas/test/test_io.py
Labels: Ready for review

#2503 FIX-#2463: Added test with callable functions as aggregate argument
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
Labels: Ready for review

#2495 TEST-#2295: Cover by tests Quoting, Compression, and File Format parameters of read_csv
  modin/pandas/test/test_io.py
Labels: Ready for review

#2484 FEAT-#2479: integrate asv
  .github/workflows/ci.yml
  .gitignore
  asv_bench/asv.conf.json
  asv_bench/benchmarks/__init__.py
  asv_bench/benchmarks/benchmarks.py
  asv_bench/benchmarks/utils.py
  environment.yml
  requirements.txt
Labels: Ready for review

#2378 FIX-#2374: remove extra code; add pandas way to handle duplicate values in reindex func for binary operations
  asv_bench/benchmarks/benchmarks.py
  modin/engines/base/frame/data.py
  modin/engines/base/frame/partition_manager.py
  modin/test/backends/pandas/test_internals.py
Labels: Ready for review

#2514 Ensure excel reader closes file if it is passed as path
  modin/config/envvars.py
  modin/engines/base/io/text/excel_dispatcher.py
  modin/pandas/test/test_io.py
  modin/pandas/test/utils.py
Labels: Ready for review

#2461 FEAT-#2375: implementation of multi-column groupby aggregation
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/data_management/functions/default_methods/groupby_default.py
  modin/data_management/functions/groupby_function.py
  modin/engines/base/frame/axis_partition.py
  modin/engines/base/frame/data.py
  modin/engines/base/frame/partition_manager.py
  modin/experimental/engines/omnisci_on_ray/frame/data.py
  modin/pandas/dataframe.py
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
  modin/utils.py
Labels: P0, Ready for review

#2443 FIX-#2442: fixed Series assignment with different indices
  .github/workflows/ci.yml
  asv_bench/benchmarks/benchmarks.py
  asv_bench/benchmarks/utils.py
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/conftest.py
  modin/engines/base/frame/data.py
  modin/engines/base/frame/partition_manager.py
  modin/experimental/backends/omnisci/query_compiler.py
  modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
  modin/pandas/dataframe.py
  modin/pandas/test/conftest.py
  modin/pandas/test/dataframe/test_indexing.py
  modin/pandas/test/dataframe/test_map_metadata.py
  modin/pandas/test/test_concat.py
  modin/pandas/test/utils.py
  modin/test/backends/base/test_internals.py
Labels: Ready for review

#2528 FIX-#2527: Use random name for hdf file test, clean file after testing
  modin/pandas/test/test_io.py
Labels: Testing :chart_with_upwards_trend:

#2469 FIX-#2169: avoid unnecessary index access in groupby
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/experimental/backends/omnisci/query_compiler.py
  modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
  modin/pandas/dataframe.py
  modin/pandas/groupby.py
Labels: Ready for review

#2532 FIX-#2498: Fix possible number of partitions for Dask engine
  modin/pandas/__init__.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#2534 FEAT-#2491: optimized groupby dictionary aggregation
  asv_bench/benchmarks/benchmarks.py
  modin/backends/pandas/query_compiler.py
  modin/data_management/functions/__init__.py
  modin/data_management/functions/groupby_function.py
  modin/engines/base/frame/data.py
  modin/engines/base/frame/partition_manager.py
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
Labels: Ready for review

#2548 FIX-#2482: improved handling non-str 'by'
  modin/backends/pandas/query_compiler.py
  modin/data_management/functions/groupby_function.py
  modin/pandas/dataframe.py
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
Labels: Ready for review

#2560 FIX-#2559: Ignore files from /proc/ when detecting file leaks
  modin/pandas/test/utils.py
Labels: Ready for review

#2562 Switch to Ray from conda-forge
  .github/workflows/ci.yml
  .github/workflows/push.yml
  environment.yml
  requirements/env_omnisci.yml
Labels: Ready for review, Testing :chart_with_upwards_trend:
