Repository modin-project/modin, pull requests merged in 2020-10, with the labels that each got.

#2228 FIX-#1965: Fix `count` func in case `numeric_only`==True
  modin/pandas/base.py
  modin/pandas/test/dataframe/test_reduction.py
Labels: Ready for review

#2196 FEAT-#2197: convert docstrings in high level APIs to numpydoc style
  .github/workflows/ci.yml
  docs/supported_apis/dataframe_supported.rst
  docs/supported_apis/series_supported.rst
  docs/supported_apis/utilities_supported.rst
  modin/pandas/__init__.py
  modin/pandas/base.py
  modin/pandas/concat.py
  modin/pandas/dataframe.py
  modin/pandas/datetimes.py
  modin/pandas/general.py
  modin/pandas/groupby.py
  modin/pandas/io.py
  modin/pandas/plotting.py
  modin/pandas/reshape.py
  modin/pandas/series.py
  modin/pandas/series_utils.py
  modin/utils.py
Labels: Code Quality :100:, documentation :bookmark_tabs:

#2150 FIX-#2093: Add ability displaying of method's name for inplace operations by progress bar
  modin/backends/pandas/query_compiler.py
Labels: Ready for review

#2208 FIX-#2181: constructing OmniSci frame from unsupported types
  modin/error_message.py
  modin/experimental/backends/omnisci/query_compiler.py
  modin/experimental/engines/omnisci_on_ray/frame/data.py
  modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py
  modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Labels: Ready for review

#2262 FIX-#1988: Fix indexing over Series via `loc` when slice is passed
  modin/pandas/indexing.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#2272 FIX-#2195: fix describe error for datasets with datetimes
  modin/backends/pandas/query_compiler.py
  modin/pandas/test/dataframe/test_reduction.py
Labels: Ready for review

#2276 FIX-#1906: fixed incorrect behaviour of 'groupby.__getattr__'
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
Labels: Ready for review

#2287 FIX-#1765: Fix support of s3 in `read_parquet`
  modin/backends/pandas/parsers.py
  modin/engines/base/frame/data.py
  modin/engines/base/io/column_stores/parquet_reader.py
  modin/pandas/test/test_io.py
  requirements/env_omnisci.yml
Labels: P0

#2302 FIX-#2285: Default to pandas warning message improved
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/data_management/functions/default_methods/binary_default.py
  modin/data_management/functions/default_methods/default.py
  modin/data_management/functions/default_methods/groupby_default.py
  modin/data_management/functions/default_methods/resample_default.py
  modin/data_management/functions/default_methods/rolling_default.py
  modin/data_management/functions/default_methods/series_default.py
  modin/pandas/test/test_general.py
Labels: Ready for review

#2306 FIX-#2258: return 'Commit Message formatting' topic
  .github/PULL_REQUEST_TEMPLATE.md
  docs/developer/contributing.rst
Labels: Ready for review

#2256 FIX-#2133 #2265: Fix binary operations in case when partitioning isn't aligned
  modin/data_management/functions/binary_function.py
  modin/engines/base/frame/data.py
  modin/pandas/series.py
  modin/pandas/test/dataframe/test_binary.py
Labels: P0, Ready for review

#2316 FIX-#2253: loc assignment fixed in case of (1, 1) shape frame
  modin/pandas/indexing.py
  modin/pandas/test/dataframe/test_indexing.py
Labels: Ready for review

#2314 FIX-#2311: fixed performance regression at reduction operations
  modin/backends/pandas/query_compiler.py
  modin/engines/base/frame/data.py
  modin/pandas/base.py
  modin/pandas/test/dataframe/test_reduction.py
Labels: Ready for review

#2216 DOCS-#2193: Add contributing doc in checklist
  docs/CONTRIBUTING.rst
  docs/index.rst
Labels: Ready for review

#2318 FIX-#1927: Fix performance issue related to `sparse` attribute access
  modin/pandas/accessor.py
  modin/pandas/dataframe.py
  modin/pandas/series.py
  modin/pandas/test/dataframe/test_default.py
  modin/pandas/test/test_api.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#2332 FIX-#2269: Move `default_to_pandas` logic from API layer to backend
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/data_management/functions/default_methods/groupby_default.py
  modin/experimental/backends/omnisci/query_compiler.py
  modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
  modin/pandas/groupby.py
  modin/pandas/test/conftest.py
Labels: Ready for review

#2323 FEAT-#2271: Add implementation of `groupby.shift`
  modin/pandas/base.py
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
  modin/pandas/test/test_series.py
Labels: P1, Ready for review
