Repository modin-project/modin, pull requests merged in 2020-09, with the labels that each got.

#1984 TEST-#1985: optimize common test dataset
  modin/pandas/test/test_dataframe.py
  modin/pandas/test/test_series.py
  modin/pandas/test/utils.py
Labels: Ready for review

#1885 REFACTOR-#1879: Move logic for `groupby.agg` into query compiler
  modin/backends/pandas/query_compiler.py
  modin/pandas/groupby.py
Labels: Ready for review

#1960 FIX-#1953: Fix computing of reduced indices for reduction operation
  modin/engines/base/frame/data.py
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/series.py
  modin/pandas/test/dataframe/test_reduction.py
  modin/pandas/test/dataframe/test_window.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#1945 FEAT-#1944: Added ability to broadcast multi-partitioned frames
  modin/engines/base/frame/partition_manager.py
  modin/engines/dask/pandas_on_dask/frame/partition_manager.py
  modin/engines/ray/pandas_on_ray/frame/partition_manager.py
  modin/pandas/dataframe.py
  modin/pandas/test/test_groupby.py
Labels: Ready for review

#1668 FIX-#1284: Series.searchsorted
  docs/supported_apis/series_supported.rst
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/pandas/series.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#1894 FEAT-#1523: 'nrows' support to 'read_csv' added
  modin/engines/base/io/text/csv_reader.py
  modin/engines/base/io/text/fwf_reader.py
  modin/engines/base/io/text/json_reader.py
  modin/engines/base/io/text/text_file_reader.py
  modin/pandas/test/data/newlines.csv
  modin/pandas/test/test_io.py
Labels: Ready for review

#1994 FIX-#1959 #1987: Fix incorrect work of `duplicated` and `drop_duplicates` functions
  modin/pandas/dataframe.py
  modin/pandas/test/dataframe/test_window.py
  modin/pandas/test/test_series.py
  modin/pandas/test/utils.py
Labels: Ready for review

#2048 FEAT-#1285: Add `sem` implementation for `Series` and `DataFrame`
  docs/supported_apis/dataframe_supported.rst
  docs/supported_apis/series_supported.rst
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/series.py
  modin/pandas/test/dataframe/test_default.py
  modin/pandas/test/dataframe/test_window.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#2055 FIX-#2054: Moved non-dependent on modin.DataFrame utils to modin/utils.py
  modin/backends/pandas/query_compiler.py
  modin/data_management/functions/groupby_function.py
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/general.py
  modin/pandas/groupby.py
  modin/pandas/io.py
  modin/pandas/plotting.py
  modin/pandas/reshape.py
  modin/pandas/series.py
  modin/pandas/test/dataframe/test_default.py
  modin/pandas/test/dataframe/test_join_sort.py
  modin/pandas/test/test_groupby.py
  modin/pandas/test/test_io.py
  modin/pandas/test/test_series.py
  modin/pandas/test/utils.py
  modin/pandas/utils.py
  modin/utils.py
Labels: Ready for review

#2060 FEAT-#2058: Improve how remote factories are defined
  modin/data_management/__init__.py
  modin/data_management/factories.py
  modin/experimental/cloud/meta_magic.py
  modin/experimental/pandas/numpy_wrap.py
  modin/pandas/__init__.py
Labels: Code Quality :100:

#2000 FIX-#1918: fix core dumped issue
  modin/engines/ray/utils.py
Labels: Ready for review

#2076 FIX-#1386: Fix `read_csv` for incorrect csv data
  modin/engines/base/io/text/csv_reader.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#2012 FIX-#1997: Fix `unstack` for MultiIndex with different inner lvl-nodes
  modin/backends/pandas/query_compiler.py
  modin/pandas/test/dataframe/test_default.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#1982 Simulate cluster for testing remote context
  modin/conftest.py
  modin/data_management/factories/factories.py
  modin/experimental/cloud/cluster.py
  modin/experimental/cloud/connection.py
  modin/experimental/cloud/local_cluster.py
  modin/pandas/__init__.py
Labels: Code Quality :100:, Ready for review, Testing :chart_with_upwards_trend:

#2086 FIX-#1997 #2084: Fix `unstack` for case when columns are non-tree MultiIndex
  modin/backends/pandas/query_compiler.py
  modin/pandas/test/dataframe/test_default.py
  modin/pandas/test/utils.py
Labels: Ready for review

#2109 Save rpyc server output if rpyc logging is on
  modin/experimental/cloud/connection.py
  modin/experimental/cloud/local_cluster.py
Labels: Testing :chart_with_upwards_trend:

#2112 FIX-#2110: get rid of 'NotImplementedError' at OmniSci query compiler
  modin/experimental/backends/omnisci/query_compiler.py
  modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
  modin/pandas/test/utils.py
Labels: Ready for review

#2111 Fix test_from_csv for simulated remote case
  .github/workflows/ci.yml
  modin/conftest.py
  modin/experimental/cloud/rpyc_proxy.py
Labels: Testing :chart_with_upwards_trend:

#2124 TEST-#2123: testing of OmniSci added at CI
  .github/workflows/ci.yml
  .github/workflows/push.yml
  requirements/env_omnisci.yml
Labels: Ready for review

#2119 Enable OmniSci on cloud
  examples/cluster/taxi-runner.py
  modin/conftest.py
  modin/data_management/factories/dispatcher.py
  modin/data_management/factories/factories.py
  modin/experimental/cloud/cluster.py
  modin/experimental/cloud/connection.py
  modin/experimental/cloud/omnisci.py
  modin/experimental/cloud/ray-autoscaler.yml
  modin/experimental/cloud/rayscale.py
  modin/pandas/__init__.py
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/series.py
Labels: OmniSci, Ready for review

#2103 FEAT-#2087 Added benchmarks test suite
  ci/benchmarks/test_benchmarks.py
  environment.yml
  requirements.txt
  requirements/df_test_requires.txt
  requirements/env_windows.yml
  requirements/windows_test_requires.txt
Labels: Ready for review

#2120 FIX-#1144: Fix `read_parquet` for working with HDFS
  modin/engines/base/io/column_stores/parquet_reader.py
Labels: Ready for review

#1669 FEAT-#1200: pivot_table implementation
  docs/supported_apis/dataframe_supported.rst
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/engines/base/frame/axis_partition.py
  modin/engines/base/frame/data.py
  modin/engines/base/frame/partition_manager.py
  modin/engines/dask/pandas_on_dask/frame/axis_partition.py
  modin/engines/ray/pandas_on_ray/frame/axis_partition.py
  modin/pandas/dataframe.py
  modin/pandas/test/dataframe/test_default.py
  modin/pandas/test/test_general.py
Labels: P1, Ready for review

#2137 FEAT-#2136: Added benchmarks for mask generation and indexing
  ci/benchmarks/test_benchmarks.py
Labels: Ready for review

#2130 FEAT-#1219, FEAT-#2135: Add `corr` and `cov` implementations for `DataFrame`
  docs/supported_apis/dataframe_supported.rst
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/pandas/dataframe.py
  modin/pandas/test/dataframe/test_default.py
  modin/pandas/test/test_groupby.py
  modin/pandas/test/utils.py
Labels: Ready for review

#2167 FEAT-#2166: Added benchmarks for DataFrame.merge
  ci/benchmarks/test_benchmarks.py
Labels: Ready for review

#2168 DOCS-#2068: Provide Jupyter notebooks showing running NYC Taxi
  examples/docker/build.sh
  examples/docker/nyc-taxi.dockerfile
  examples/docker/nyc-taxi.py
  examples/jupyter/NYC_Taxi.ipynb
  examples/jupyter/NYC_Taxi_cloud.ipynb
Labels: Ready for review, documentation :bookmark_tabs:
