Repository modin-project/modin, pull requests merged in 2020-07, with the labels that each got.

#1676 Fixed #1675. Added setting parent in loc and iloc
  modin/pandas/dataframe.py
  modin/pandas/indexing.py
  modin/pandas/series.py
  modin/pandas/test/test_dataframe.py
Labels: Ready for review

#1521 Add `corr` implementation for `Series`
  docs/supported_apis/series_supported.rst
  modin/pandas/series.py
  modin/pandas/test/test_dataframe.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#1672 enable ray as a default engine for windows
  .github/workflows/ci.yml
  .github/workflows/push.yml
  modin/__init__.py
  setup.py
Labels: Ready for review

#1567 Level parameter for kurt function implementation
  docs/supported_apis/dataframe_supported.rst
  docs/supported_apis/series_supported.rst
  modin/pandas/base.py
  modin/pandas/test/test_dataframe.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#1687 Add `autocorr` implementation for `Series`
  docs/supported_apis/series_supported.rst
  modin/pandas/series.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#1694 Implement a method to switch a pair of engine and partition
  modin/__init__.py
  modin/data_management/test/test_dispatcher.py
Labels: Ready for review

#1703 Fix of issue #1462: groupby_agg ignores exceptions
  modin/backends/pandas/query_compiler.py
  modin/pandas/groupby.py
  modin/pandas/test/test_dataframe.py
  modin/pandas/test/test_groupby.py
  modin/pandas/test/utils.py
Labels: Ready for review

#1625 Add `resample` implementation for Series and DataFrame
  docs/supported_apis/dataframe_supported.rst
  docs/supported_apis/series_supported.rst
  modin/backends/pandas/query_compiler.py
  modin/pandas/base.py
  modin/pandas/test/test_dataframe.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#1665 refactor initialize_ray
  modin/engines/ray/utils.py
  modin/pandas/__init__.py
Labels: Ready for review

#1702 Implement cluster spawning API
  examples/cluster/experimental_cloud.py
  modin/experimental/cloud/__init__.py
  modin/experimental/cloud/base.py
  modin/experimental/cloud/cluster.py
  modin/experimental/cloud/connection.py
  modin/experimental/cloud/ray-autoscaler.yml
  modin/experimental/cloud/rayscale.py
Labels: Ray :zap:, Ready for review

#1717 Fix for Series.attrs and Series.array
  modin/pandas/series.py
  modin/pandas/test/test_series.py
  modin/pandas/test/utils.py
Labels: Ready for review

#1695 Add `merge` implementation for `DataFrame` and as free function
  docs/supported_apis/dataframe_supported.rst
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/data_management/utils.py
  modin/engines/base/frame/data.py
  modin/engines/base/frame/partition_manager.py
  modin/engines/dask/pandas_on_dask/frame/partition_manager.py
  modin/engines/ray/pandas_on_ray/frame/partition_manager.py
  modin/pandas/dataframe.py
  modin/pandas/general.py
  modin/pandas/test/test_dataframe.py
  modin/pandas/test/test_general.py
Labels: P1, Ready for review

#1754 Move logic of `sort_values` into the query compiler
  modin/backends/pandas/query_compiler.py
  modin/pandas/base.py
  modin/pandas/test/test_dataframe.py
Labels: P1

#1753 Improve performance of slice indexing
  modin/engines/base/frame/data.py
  modin/engines/dask/pandas_on_dask/frame/partition.py
  modin/engines/python/pandas_on_python/frame/partition.py
  modin/engines/ray/pandas_on_ray/frame/partition.py
  modin/pandas/indexing.py
Labels: Performance 🚀

#1684 [FIX] Fix #1683 - losing index names in pd.concat
  modin/pandas/concat.py
  modin/pandas/test/test_concat.py
  modin/pandas/test/utils.py
Labels: Ready for review

#1719 REFACTOR-#1741: Use low-level api for kurt function implementation with defined level parameter
  modin/pandas/base.py
Labels: Ready for review

#1727 [FIX] Fix of inconsistent indices #1726 #1731 #1732 #1734
  modin/backends/pandas/query_compiler.py
  modin/data_management/functions/binary_function.py
  modin/data_management/functions/groupby_function.py
  modin/engines/base/frame/data.py
  modin/engines/ray/generic/io.py
  modin/pandas/groupby.py
  modin/pandas/test/test_general.py
  modin/pandas/test/test_io.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#1782 FEAT-#1781: implement ClusterError.__str__
  modin/experimental/cloud/base.py
Labels: Ready for review

#1758 FEAT-#1194 #1283 #1138: Add `Series.rolling`, `DataFrame.rolling`
  .github/workflows/ci.yml
  .github/workflows/push.yml
  docs/supported_apis/dataframe_supported.rst
  docs/supported_apis/series_supported.rst
  modin/backends/pandas/query_compiler.py
  modin/pandas/base.py
  modin/pandas/test/test_dataframe.py
  modin/pandas/test/test_rolling.py
  modin/pandas/test/test_series.py
Labels: P1, Ready for review

#1764 REFACTOR-#1763: Move logic of `merge` into the query compiler
  modin/backends/pandas/query_compiler.py
  modin/data_management/utils.py
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/test/test_dataframe.py
Labels: Ready for review

#1689 FEAT-#1205: melt implementation
  docs/supported_apis/dataframe_supported.rst
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/engines/base/frame/data.py
  modin/engines/base/frame/partition_manager.py
  modin/error_message.py
  modin/pandas/dataframe.py
  modin/pandas/test/test_dataframe.py
Labels: P1, Ready for review

#1744 TEST-#1779: Limit object store to 1GB during CI tests
  .github/workflows/ci.yml
  .github/workflows/push.yml
Labels: Code Quality :100:, Memory :floppy_disk:, Needs Review, Ray :zap:, Ready for review, Regression :leftwards_arrow_with_hook:, Testing :chart_with_upwards_trend:

#1820 FIX-#1457: Series.reset_index considering 'name' fix
  modin/pandas/series.py
  modin/pandas/test/test_series.py
  modin/pandas/test/utils.py
Labels: Ready for review

#1828 FIX-#1459: 'to_pandas' of nested objects added
  modin/pandas/base.py
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
  modin/pandas/utils.py
Labels: Ready for review

#1730 FIX-#1729: Fix incorrect result of `Series.dt.components/freq/tz`
  modin/backends/pandas/query_compiler.py
  modin/engines/base/frame/data.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#1802 FIX-#1426: Groupby on categories fixed
  modin/backends/pandas/query_compiler.py
  modin/data_management/functions/groupby_function.py
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
  modin/pandas/test/utils.py
Labels: Ready for review

#1827 FIX-#1464: product/sum incorrect behavior of 'min_count' fixed
  modin/pandas/dataframe.py
  modin/pandas/test/test_dataframe.py
  modin/pandas/test/test_series.py
  modin/pandas/test/utils.py
Labels: Ready for review

#1858 FIX-#1857: make 'sort_index' consider axis parameter
  modin/backends/pandas/query_compiler.py
  modin/pandas/test/test_dataframe.py
Labels: Ready for review

#1845 FIX-#1154: properly process UDFs
  modin/backends/pandas/query_compiler.py
  modin/engines/base/frame/data.py
  modin/pandas/base.py
  modin/pandas/groupby.py
  modin/pandas/test/test_dataframe.py
  modin/pandas/test/utils.py
  modin/pandas/utils.py
Labels: Ready for review
