Repository modin-project/modin, pull requests merged in 2021-12, with the labels that each got.

#3511 FIX-#3510: Correct processing of callable `skiprows` parameter of `read_csv` function
  modin/core/io/text/text_file_dispatcher.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#3757 FIX-#3756: compare all of the groups in GroupBy objects comparator
  modin/pandas/test/test_groupby.py
Labels: Testing 📈

#3754 FIX-#3749: Remove providing of `address` for `ray.init` in case local cluster
  modin/core/execution/ray/common/utils.py
Labels: Ready for review

#3773 FIX-#3772: Fix failures flake8 in CI
  modin/pandas/test/test_groupby.py
Labels: Ready for review, P0

#3770 FIX-#3767: Fix tests for Modin XGB Dmatrix
  modin/experimental/xgboost/test/test_dmatrix.py
Labels: Ready for review, P0

#3775 DOCS-#3719: Improve documentation for `pandas_on_python` execution
  docs/flow/modin/core/execution/python/implementations/pandas_on_python/index.rst
  docs/img/pandas_on_python_data_egress.svg
  docs/img/pandas_on_python_data_ingress.svg
  docs/img/pandas_on_python_data_transform.svg
Labels: P1, Ready for review

#3640 DOCS-#3064: Improve Component view part in docs
  docs/developer/architecture.rst
  docs/flow/modin/core/execution/dask/implementations/pandas_on_dask/index.rst
  docs/flow/modin/core/execution/python/implementations/pandas_on_python/index.rst
  docs/flow/modin/core/execution/ray/implementations/cudf_on_ray/index.rst
  docs/flow/modin/core/execution/ray/implementations/pandas_on_ray/index.rst
  docs/flow/modin/core/storage_formats/index.rst
  docs/flow/modin/experimental/index.rst
  docs/img/generic_data_egress.svg
  docs/img/generic_data_ingress.svg
  docs/img/generic_data_transform.svg
Labels: P0

#3785 DOCS-#3776: Improve documentation for `pandas_on_dask` execution
  docs/flow/modin/core/execution/dask/implementations/pandas_on_dask/index.rst
  docs/img/pandas_on_dask_data_egress.svg
  docs/img/pandas_on_dask_data_ingress.svg
  docs/img/pandas_on_dask_data_transform.svg
Labels: P1, Ready for review

#3809 DOCS-#3782: Add `using_pandas_on_python.rst` doc
  docs/developer/architecture.rst
  docs/developer/index.rst
  docs/developer/using_pandas_on_python.rst
  docs/flow/modin/core/execution/python/implementations/pandas_on_python/index.rst
Labels: documentation 📜, Ready for review

#3783 FIX-#3774: Fix omnisci import
  docs/developer/troubleshooting.rst
  docs/developer/using_omnisci.rst
  modin/config/envvars.py
  modin/core/storage_formats/pyarrow/query_compiler.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/utils.py
  setup.cfg
Labels: P0, Backport :back:

#3753 DOCS-#3752: improve documentation of `OmnisciOnNative` execution
  docs/flow/modin/experimental/core/execution/native/implementations/omnisci_on_native/index.rst
  docs/flow/modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_engine.rst
  docs/img/omnisci/omnisci_calcite_serialization_flow.svg
  docs/img/omnisci/omnisci_import.svg
  docs/img/omnisci/omnisci_ingress.svg
  docs/img/omnisci/omnisci_lazy_tree_example.svg
  docs/img/omnisci/omnisci_query_flow.svg
Labels: documentation 📜, P1, Ready for review

#3742 FIX-#3741: Added delivery of the data argument to df
  .github/workflows/ci.yml
  modin/experimental/cloud/rpyc_proxy.py
Labels: Backport :back:

#3857 DOCS-#3856: add dispatchers, parsers and factories public classes
  docs/flow/modin/core/execution/dispatching.rst
  docs/flow/modin/core/io/index.rst
  docs/flow/modin/core/storage_formats/pandas/parsers.rst
Labels: Ready for review

#3819 DOCS-#3811: improve documentation for experimental 'pandas on Ray'
  docs/advanced_usage/index.rst
  docs/developer/architecture.rst
  docs/flow/modin/experimental/core/execution/ray/implementations/pandas_on_ray/index.rst
  docs/flow/modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/index.rst
  modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/experimental/pandas/io.py
Labels: Ready for review

#3851 DOCS-#3850: Elaborate on modin.core.dataframe.base and .pandas
  docs/flow/modin/core/dataframe/base/index.rst
  docs/flow/modin/core/dataframe/base/partitioning/axis_partition.rst
  docs/flow/modin/core/dataframe/pandas/dataframe.rst
  docs/flow/modin/core/dataframe/pandas/index.rst
  docs/flow/modin/core/dataframe/pandas/partitioning/axis_partition.rst
Labels: documentation 📜

#3830 FEAT-#3829: Add support of `storage_options` for `read_csv_glob`
  modin/core/storage_formats/pandas/parsers.py
  modin/experimental/pandas/test/test_io_exp.py
Labels: Ready for review

#3862 REFACTOR-#3861: move 'SignalActor' class into task_wrapper.py
  modin/core/execution/ray/common/task_wrapper.py
  modin/core/execution/ray/common/utils.py
  modin/core/execution/ray/generic/io/io.py
Labels: Ready for review

#3523 FIX-#3498 Fix groupby to use kwargs for getting the groups
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
  modin/pandas/test/utils.py
Labels: Ready for review
