Repository modin-project/modin, pull requests merged in 2021-11, with the labels that each got.

#3564 FIX-#3420: update cloud images
  examples/cluster/h2o-runner.py
  examples/cluster/mortgage-runner.py
  examples/cluster/taxi-runner.py
Labels: Ready for review

#3520 REFACTOR-#3519: align `mask` interface with its docstring
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/core/dataframe/pandas/partitioning/partition_manager.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
  modin/core/storage_formats/base/query_compiler.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py
  modin/pandas/indexing.py
  modin/pandas/test/dataframe/test_indexing.py
  modin/test/storage_formats/pandas/test_internals.py
Labels: Ready for review

#3552 FIX-#2301: Add support of `storage_options` in `read_*`
  modin/core/io/column_stores/feather_dispatcher.py
  modin/core/io/file_dispatcher.py
  modin/core/io/text/csv_dispatcher.py
  modin/core/storage_formats/pandas/parsers.py
  modin/pandas/test/test_io.py
Labels: Ready for review, P0

#3540 REFACTOR-#3539: align read_fwf with read_csv
  modin/core/io/text/csv_dispatcher.py
  modin/core/io/text/fwf_dispatcher.py
  modin/core/io/text/text_file_dispatcher.py
  modin/core/storage_formats/pandas/parsers.py
  modin/pandas/io.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#3633 DOCS-#3632: Add Google Colab setup instructions
  docs/installation.rst
Labels: documentation 📜

#3575 FIX-#3551: fix hanging behaviour for to_csv
  modin/core/execution/ray/common/utils.py
  modin/core/execution/ray/generic/io/io.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#3713 DOCS-#3712: Clarify GitHub release naming
  docs/release-procedure.md
Labels: documentation 📜

#3711 TEST-#3710: add groupby benchmarks with dict aggregation for omnisci
  asv_bench/benchmarks/omnisci/benchmarks.py
Labels: Ready for review

#3613 FEAT-#3303: Add __getitem__ for Resampler
  modin/pandas/base.py
  modin/pandas/test/dataframe/test_default.py
Labels: Ready for review

#3579 FIX-#1900: Fix `groupby` for case `by` is None
  modin/core/storage_formats/pandas/query_compiler.py
  modin/pandas/dataframe.py
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
Labels: P1, Ready for review

#3714 TEST-#3708: use 'latest' tag for 'rayproject/ray' base Ray image
  ci/teamcity/Dockerfile.teamcity-ci
Labels: Ready for review

#3611 DOCS-#3610: Add section about handling of `read_csv` `skiprows` parameter
  docs/flow/modin/core/io/index.rst
Labels: Ready for review
