Repository modin-project/modin, pull requests merged in 2021-05, with the labels that each got.

#3026 FIX-#3025: use pandas.DataFrame as return value
  modin/engines/ray/generic/io.py
Labels: Ready for review

#3032 FIX-#3031: Added -n 2 to long running pytest tasks and paralellized windows tasks
  .github/workflows/ci.yml
  .github/workflows/push.yml
Labels: Ready for review

#3001 Improve doc checker
  .github/workflows/ci.yml
  asv_bench/benchmarks/utils.py
  modin/engines/base/frame/data.py
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/general.py
  modin/pandas/groupby.py
  modin/pandas/io.py
  modin/pandas/plotting.py
  modin/pandas/series.py
  modin/pandas/series_utils.py
  modin/test/test_utils.py
  modin/utils.py
  scripts/doc_checker.py
  scripts/test/examples.py
  scripts/test/test_doc_checker.py
Labels: Ready for review

#3047 FIX-#3046: Implemented codecov script hashsum verification before exe…
  .github/workflows/ci.yml
  .github/workflows/push.yml
Labels: Ready for review

#3034 Fix docstring inheritance
  modin/test/test_utils.py
  modin/utils.py
Labels: Ready for review

#3055 FIX-#3054: Update node.js 10->12
  .github/workflows/ci.yml
Labels: P0, Ready for review

#3028 FIX-#3027: Removed unnecessary 'str.repeats' function, fixed test
  modin/pandas/series_utils.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#2975 Fixed bug in sort_values related to handling ignore_index and key parameters
  modin/backends/pandas/query_compiler.py
  modin/pandas/test/dataframe/test_join_sort.py
  modin/pandas/test/utils.py
Labels: Ready for review

#3016 DOCS-#3015: Document `modin.experimental.sklearn` module
  .github/workflows/ci.yml
  docs/developer/architecture.rst
  docs/flow/modin/experimental/index.rst
  docs/flow/modin/experimental/sklearn.rst
  modin/experimental/sklearn/__init__.py
  modin/experimental/sklearn/model_selection/__init__.py
  modin/experimental/sklearn/model_selection/train_test_split.py
Labels: Ready for review

#2812 FIX-#2811: fix 'groupby.size' for Series
  modin/backends/pandas/query_compiler.py
  modin/data_management/functions/groupby_function.py
  modin/pandas/groupby.py
  modin/pandas/test/test_groupby.py
Labels: Ready for review

#2964 DOCS-#2963: document modin.experimental.pandas
  .github/workflows/ci.yml
  docs/developer/architecture.rst
  docs/flow/modin/experimental/pandas.rst
  modin/experimental/engines/pandas_on_ray/sql.py
  modin/experimental/pandas/__init__.py
  modin/experimental/pandas/io_exp.py
  modin/experimental/pandas/numpy_wrap.py
Labels: Ready for review

#3022 Add docstrings in modin.pandas.[groupby, indexing, accessor, iterator, plotting, series_utils, io, general]
  .github/workflows/ci.yml
  modin/pandas/accessor.py
  modin/pandas/general.py
  modin/pandas/groupby.py
  modin/pandas/indexing.py
  modin/pandas/iterator.py
  modin/pandas/plotting.py
  modin/pandas/series_utils.py
  modin/pandas/utils.py
Labels: Ready for review

#2915 FIX-#2697: fix modin cloud with numpy==1.20
  environment-dev.yml
  modin/conftest.py
  requirements-dev.txt
  requirements/requirements-no-engine.yml
  setup.py
Labels: P1, Ready for review

#2965 DOCS-#2947: Update docs for `modin.experimental.xgboost` module
  .github/workflows/ci.yml
  docs/conf.py
  docs/developer/architecture.rst
  docs/flow/modin/experimental/index.rst
  docs/flow/modin/experimental/xgboost.rst
  docs/modin_xgboost.rst
  modin/experimental/xgboost/__init__.py
  modin/experimental/xgboost/test/__init__.py
  modin/experimental/xgboost/utils.py
  modin/experimental/xgboost/xgboost.py
  modin/experimental/xgboost/xgboost_ray.py
Labels: Ready for review

#3074 Fix check for unsupported columns if a column starts with a N/A value
  modin/experimental/engines/omnisci_on_ray/frame/partition_manager.py
  modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Labels: Ready for review

#3000 Add documentation to modin/pandas/base.py
  .github/workflows/ci.yml
  docs/developer/architecture.rst
  docs/flow/modin/pandas/base.rst
  modin/pandas/base.py
Labels: Ready for review

#2956 DOCS-#2941: document `modin/data_management` module
  .github/workflows/ci.yml
  docs/developer/architecture.rst
  docs/flow/modin/data_management/factories.rst
  docs/flow/modin/data_management/functions.rst
  docs/img/binary_evaluation.svg
  docs/img/engine_dispatching.svg
  docs/img/map_evaluation.svg
  docs/img/reduce_evaluation.svg
  docs/supported_apis/index.rst
  modin/data_management/factories/__init__.py
  modin/data_management/factories/dispatcher.py
  modin/data_management/factories/factories.py
  modin/data_management/functions/__init__.py
  modin/data_management/functions/binary_function.py
  modin/data_management/functions/default_methods/__init__.py
  modin/data_management/functions/default_methods/any_default.py
  modin/data_management/functions/default_methods/binary_default.py
  modin/data_management/functions/default_methods/cat_default.py
  modin/data_management/functions/default_methods/dataframe_default.py
  modin/data_management/functions/default_methods/datetime_default.py
  modin/data_management/functions/default_methods/default.py
  modin/data_management/functions/default_methods/groupby_default.py
  modin/data_management/functions/default_methods/resample_default.py
  modin/data_management/functions/default_methods/rolling_default.py
  modin/data_management/functions/default_methods/series_default.py
  modin/data_management/functions/default_methods/str_default.py
  modin/data_management/functions/foldfunction.py
  modin/data_management/functions/function.py
  modin/data_management/functions/groupby_function.py
  modin/data_management/functions/mapfunction.py
  modin/data_management/functions/mapreducefunction.py
  modin/data_management/functions/reductionfunction.py
  modin/data_management/utils.py
Labels: Ready for review

#3005 DOCS-#2986: Document `modin.experimental.engines.{pandas_on_ray, pyarrow_on_ray}`
  .github/workflows/ci.yml
  docs/developer/architecture.rst
  docs/flow/modin/experimental/engines/pandas_on_ray.rst
  docs/flow/modin/experimental/engines/pyarrow_on_ray.rst
  docs/flow/modin/experimental/experimental.rst
  modin/engines/base/io/text/csv_glob_dispatcher.py
  modin/experimental/engines/pandas_on_ray/__init__.py
  modin/experimental/engines/pandas_on_ray/io_exp.py
  modin/experimental/engines/pandas_on_ray/sql.py
  modin/experimental/engines/pyarrow_on_ray/__init__.py
  modin/experimental/engines/pyarrow_on_ray/frame/__init__.py
  modin/experimental/engines/pyarrow_on_ray/frame/axis_partition.py
  modin/experimental/engines/pyarrow_on_ray/frame/data.py
  modin/experimental/engines/pyarrow_on_ray/frame/partition.py
  modin/experimental/engines/pyarrow_on_ray/frame/partition_manager.py
  modin/experimental/engines/pyarrow_on_ray/io.py
  scripts/doc_checker.py
Labels: Ready for review

#3041 DOCS-#3040: document `modin.backends.pandas`
  .github/workflows/ci.yml
  docs/developer/architecture.rst
  docs/flow/modin/backends/pandas/index.rst
  docs/flow/modin/backends/pandas/parsers.rst
  docs/flow/modin/backends/pandas/query_compiler.rst
  modin/backends/pandas/__init__.py
  modin/backends/pandas/query_compiler.py
Labels: Ready for review

#3024 DOCS-#3023: Document `modin.engines.dask`
  .github/workflows/ci.yml
  docs/developer/architecture.rst
  docs/flow/modin/engines/base/frame/axis_partition.rst
  docs/flow/modin/engines/base/frame/partition.rst
  docs/flow/modin/engines/dask/pandas_on_dask/frame/axis_partition.rst
  docs/flow/modin/engines/dask/pandas_on_dask/frame/data.rst
  docs/flow/modin/engines/dask/pandas_on_dask/frame/index.rst
  docs/flow/modin/engines/dask/pandas_on_dask/frame/partition.rst
  docs/flow/modin/engines/dask/pandas_on_dask/frame/partition_manager.rst
  modin/engines/dask/__init__.py
  modin/engines/dask/pandas_on_dask/__init__.py
  modin/engines/dask/pandas_on_dask/frame/__init__.py
  modin/engines/dask/pandas_on_dask/frame/axis_partition.py
  modin/engines/dask/pandas_on_dask/frame/data.py
  modin/engines/dask/pandas_on_dask/frame/partition.py
  modin/engines/dask/pandas_on_dask/frame/partition_manager.py
  modin/engines/dask/pandas_on_dask/io.py
  modin/engines/dask/task_wrapper.py
  modin/engines/dask/utils.py
Labels: Ready for review

#3087 DOCS-#3086: fix links and warnings in the docs
  docs/UsingSQLonRay/index.rst
  docs/developer/architecture.rst
  docs/experimental_features/index.rst
  docs/flow/modin/backends/pandas/index.rst
Labels: Ready for review
