Repository modin-project/modin, pull requests merged in 2021-06, with the labels that each got.

#2993 DOCS-#2944: Document `modin.engines.ray`
  .github/workflows/ci.yml
  docs/conf.py
  docs/developer/architecture.rst
  docs/flow/modin/engines/ray/cudf_on_ray/frame/axis_partition.rst
  docs/flow/modin/engines/ray/cudf_on_ray/frame/data.rst
  docs/flow/modin/engines/ray/cudf_on_ray/frame/gpu_manager.rst
  docs/flow/modin/engines/ray/cudf_on_ray/frame/index.rst
  docs/flow/modin/engines/ray/cudf_on_ray/frame/partition.rst
  docs/flow/modin/engines/ray/cudf_on_ray/frame/partition_manager.rst
  docs/flow/modin/engines/ray/cudf_on_ray/io.rst
  docs/flow/modin/engines/ray/generic.rst
  docs/flow/modin/engines/ray/pandas_on_ray/frame/axis_partition.rst
  docs/flow/modin/engines/ray/pandas_on_ray/frame/data.rst
  docs/flow/modin/engines/ray/pandas_on_ray/frame/index.rst
  docs/flow/modin/engines/ray/pandas_on_ray/frame/partition.rst
  docs/flow/modin/engines/ray/pandas_on_ray/frame/partition_manager.rst
  modin/engines/ray/cudf_on_ray/__init__.py
  modin/engines/ray/cudf_on_ray/frame/__init__.py
  modin/engines/ray/cudf_on_ray/frame/axis_partition.py
  modin/engines/ray/cudf_on_ray/frame/data.py
  modin/engines/ray/cudf_on_ray/frame/gpu_manager.py
  modin/engines/ray/cudf_on_ray/frame/partition.py
  modin/engines/ray/cudf_on_ray/frame/partition_manager.py
  modin/engines/ray/cudf_on_ray/io/__init__.py
  modin/engines/ray/cudf_on_ray/io/io.py
  modin/engines/ray/cudf_on_ray/io/text/__init__.py
  modin/engines/ray/cudf_on_ray/io/text/csv_dispatcher.py
  modin/engines/ray/generic/frame/partition_manager.py
  modin/engines/ray/generic/io.py
  modin/engines/ray/pandas_on_ray/frame/axis_partition.py
  modin/engines/ray/pandas_on_ray/frame/data.py
  modin/engines/ray/pandas_on_ray/frame/modin_aqp.py
  modin/engines/ray/pandas_on_ray/frame/partition.py
  modin/engines/ray/pandas_on_ray/frame/partition_manager.py
  modin/engines/ray/pandas_on_ray/io.py
  modin/engines/ray/task_wrapper.py
  modin/engines/ray/utils.py
  scripts/doc_checker.py
Labels: Ready for review

#3056 DOCS-#3037: Document `modin.pandas.series`
  .github/workflows/ci.yml
  docs/developer/architecture.rst
  docs/flow/modin/pandas/series.rst
  modin/pandas/series.py
Labels: Ready for review

#3094 FEAT-#3093: Fix omnisci dbe import on windows
  modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.py
Labels: OmniSci

#3067 DOCS-#3060: Document `modin.engines.python`
  .github/workflows/ci.yml
  docs/_templates/layout.html
  docs/developer/architecture.rst
  docs/flow/modin/engines/python/pandas_on_python/frame/axis_partition.rst
  docs/flow/modin/engines/python/pandas_on_python/frame/data.rst
  docs/flow/modin/engines/python/pandas_on_python/frame/index.rst
  docs/flow/modin/engines/python/pandas_on_python/frame/partition.rst
  docs/flow/modin/engines/python/pandas_on_python/frame/partition_manager.rst
  modin/engines/python/pandas_on_python/__init__.py
  modin/engines/python/pandas_on_python/frame/__init__.py
  modin/engines/python/pandas_on_python/frame/axis_partition.py
  modin/engines/python/pandas_on_python/frame/data.py
  modin/engines/python/pandas_on_python/frame/partition.py
  modin/engines/python/pandas_on_python/frame/partition_manager.py
  modin/engines/python/pandas_on_python/io.py
Labels: Ready for review

#3120 FIX-#3116: Add variable to be able to set Redis password
  modin/config/envvars.py
  modin/engines/ray/utils.py
Labels: Ready for review

#3051 DOCS-#3048: document `modin.backends.pyarrow` module
  .github/workflows/ci.yml
  docs/conf.py
  docs/developer/architecture.rst
  docs/flow/modin/backends/pyarrow/index.rst
  docs/flow/modin/backends/pyarrow/parsers.rst
  docs/flow/modin/backends/pyarrow/query_compiler.rst
  modin/backends/pyarrow/__init__.py
  modin/backends/pyarrow/parsers.py
  modin/backends/pyarrow/query_compiler.py
Labels: Ready for review

#3109 DOCS-#3088: Document `modin.pandas.dataframe`
  .github/workflows/ci.yml
  docs/developer/architecture.rst
  docs/flow/modin/pandas/dataframe.rst
  modin/pandas/dataframe.py
Labels: Ready for review

#3129 DOCS-#3112: Document `modin.config`
  .github/workflows/ci.yml
  docs/conf.py
  docs/developer/architecture.rst
  docs/flow/modin/config.rst
  modin/config/__init__.py
  modin/config/__main__.py
  modin/config/envvars.py
  modin/config/pubsub.py
Labels: Ready for review

#3152 FIX-#3150: fix defaulting to pandas for reduction operations at OmniSci backend
  modin/experimental/backends/omnisci/query_compiler.py
  modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Labels: OmniSci, Ready for review

#3162 FIX-#3160: handle columns metadata more carefully at 'reset_index'
  modin/experimental/engines/omnisci_on_ray/frame/data.py
  modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Labels: OmniSci, Ready for review

#2864 FIX-#2803: Implement Modin efficient fillna with DataFrame/Series value
  modin/backends/base/query_compiler.py
  modin/backends/pandas/query_compiler.py
  modin/experimental/backends/omnisci/query_compiler.py
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/series.py
  modin/pandas/test/dataframe/test_window.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#3175 DOCS-#3168: Fix inconsistencies in the `modin.config` docs
  modin/config/__main__.py
Labels: Ready for review

#2958 TEST-#2951: add ASV config for omnisci backend
  .github/workflows/ci.yml
  asv_bench/asv.conf.omnisci.json
  asv_bench/benchmarks/omnisci/__init__.py
  asv_bench/benchmarks/omnisci/benchmarks.py
  asv_bench/benchmarks/omnisci/io.py
  asv_bench/benchmarks/omnisci/utils.py
  asv_bench/benchmarks/scalability/scalability_benchmarks.py
  asv_bench/benchmarks/utils.py
  environment-dev.yml
  requirements-dev.txt
  requirements/requirements-no-engine.yml
Labels: Ready for review

#3184 FIX-#3182: add real_numpy to _EXCLUDE_MODULES
  environment-dev.yml
  modin/experimental/pandas/numpy_wrap.py
  modin/pandas/test/test_io.py
  requirements-dev.txt
  requirements/env_omnisci.yml
  requirements/requirements-no-engine.yml
  setup.py
Labels: Ready for review

#3190 FIX-#3181: Update install command for Ray
  environment-dev.yml
  requirements-dev.txt
  setup.py
Labels: Ready for review

#3187 FIX-#3186: disable OmniSci' watchdog by default
  modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.py
Labels: OmniSci, Ready for review

#3174 FIX-#3173: fix `push-to-master` test
  environment-dev.yml
  requirements-dev.txt
  requirements/requirements-no-engine.yml
Labels: Ready for review

#3158 FEAT-#3155: add 'DataFrame.nunique' implementation for OmniSci backend
  modin/experimental/backends/omnisci/query_compiler.py
  modin/experimental/engines/omnisci_on_ray/frame/data.py
  modin/experimental/engines/omnisci_on_ray/test/test_dataframe.py
Labels: OmniSci

#3156 FIX-#3151: Fix default size of Ray obj store memory
  modin/engines/ray/utils.py
Labels: Ready for review
