Repository modin-project/modin, pull requests merged in 2021-09, with the labels that each got.

#3244 FEAT-#3243: Add async execution support for Modin xgb.predict
  docs/flow/modin/experimental/xgboost.rst
  modin/experimental/xgboost/test/test_xgboost.py
  modin/experimental/xgboost/xgboost.py
  modin/experimental/xgboost/xgboost_ray.py
Labels: Ready for review

#3382 FIX-#3381: JSON dispatcher data file split correction
  modin/engines/base/io/text/json_dispatcher.py
Labels: Ready for review

#3390 TEST-#3389: remove unnecessary data sizes for ASV benchmarks
  asv_bench/benchmarks/utils/data_shapes.py
Labels: Ready for review

#3365 TEST-#3364: add value_counts benchmark for OmniSci backend (dataframe case)
  asv_bench/benchmarks/omnisci/benchmarks.py
  asv_bench/benchmarks/utils/data_shapes.py
Labels: Ready for review

#3386 FEAT-#3126: use MODIN_MEMORY to specify memory for dask engine
  modin/config/envvars.py
  modin/engines/dask/utils.py
Labels: Ready for review

#3408 FIX-#3407: change type of series shape
  asv_bench/benchmarks/utils/data_shapes.py
Labels: Ready for review

#3402 FIX-#3401: all shapes don't depend on MODIN_BACKEND env
  asv_bench/benchmarks/utils/data_shapes.py
Labels: Ready for review

#3398 FEAT-#2006: support local variables in query and eval
  modin/backends/pandas/query_compiler.py
  modin/pandas/dataframe.py
  modin/pandas/test/dataframe/test_udf.py
Labels: Ready for review

#3399 Improve containerized benchmark examples
  examples/docker/build.sh
  examples/docker/census-on-omnisci/build-docker-image.sh
  examples/docker/census-on-omnisci/census-omnisci.dockerfile
  examples/docker/modin-omnisci/Dockerfile
  examples/docker/modin-omnisci/build-docker-image.sh
  examples/docker/modin-omnisci/census-omnisci.py
  examples/docker/modin-omnisci/nyc-taxi-omnisci.py
  examples/docker/modin-omnisci/plasticc-omnisci.py
  examples/docker/modin-ray/Dockerfile
  examples/docker/modin-ray/build-docker-image.sh
  examples/docker/modin-ray/census.py
  examples/docker/modin-ray/nyc-taxi.py
  examples/docker/modin-ray/plasticc.py
  examples/docker/nyc-taxi.dockerfile
  examples/docker/nyc-taxi.py
  examples/docker/plasticc-on-omnisci/build-docker-image.sh
  examples/docker/plasticc-on-omnisci/plasticc-omnisci.dockerfile
  examples/docker/taxi-on-omnisci/build-docker-image.sh
  examples/docker/taxi-on-omnisci/nyc-taxi-omnisci.dockerfile
Labels: Ready for review

#3377 FIX-#3242: Fix processing of `evals` parameter in Modin xgb
  modin/experimental/xgboost/test/test_xgboost.py
  modin/experimental/xgboost/xgboost_ray.py
Labels: Ready for review

#3440 FIX-#3439: Remove inheritance of Modin DMatrix from `xgb.DMatrix`
  modin/experimental/xgboost/xgboost.py
Labels: Ready for review

#3397 FIX-#3395: Make `label` param of DMatrix optional
  modin/experimental/xgboost/xgboost.py
Labels: Ready for review

#3436 DOCS-#3414: correct OmnisciOnNative stuff in docs
  CODEOWNERS
  docs/UsingOmnisci/index.rst
  docs/developer/architecture.rst
  docs/flow/modin/experimental/backends/omnisci/query_compiler.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/calcite_algebra.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/calcite_builder.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/calcite_serializer.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/data.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/df_algebra.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/expr.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/index.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/omnisci_worker.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/partition.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/frame/partition_manager.rst
  docs/flow/modin/experimental/engines/omnisci_on_native/omnisci_engine.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/axis_partition.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/calcite_algebra.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/calcite_builder.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/calcite_serializer.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/data.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/df_algebra.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/expr.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/omnisci_worker.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/partition.rst
  docs/flow/modin/experimental/engines/omnisci_on_ray/frame/partition_manager.rst
  docs/img/factory_dispatching.svg
Labels: Ready for review

#3438 FIX-#3437: Warn user about heterogeneous data presence during read_csv call and propose workaround
  docs/troubleshooting.rst
  modin/backends/pandas/parsers.py
Labels: Ready for review

#3473 TEST-#3474: fix pip install commmand in push-to-master
  .github/workflows/push-to-master.yml
Labels: Ready for review

#3423 TEST-#3422: always import read data to OmniSci in IO tests
  modin/experimental/engines/omnisci_on_native/test/test_dataframe.py
  modin/experimental/engines/omnisci_on_native/test/utils.py
  modin/pandas/test/test_io.py
  modin/pandas/test/utils.py
Labels: Ready for review, OmniSci

#3462 FIX-#3461: allow `FrameNode` to be a GroupBy key
  modin/experimental/engines/omnisci_on_native/frame/data.py
  modin/experimental/engines/omnisci_on_native/test/test_dataframe.py
Labels: Ready for review, OmniSci

#3308 FIX-#3216: update Arrow to 3.0 for OmniSci backend
  modin/experimental/engines/omnisci_on_native/frame/omnisci_worker.py
  modin/experimental/engines/omnisci_on_native/test/test_dataframe.py
  modin/experimental/engines/omnisci_on_native/test/utils.py
  modin/pandas/test/test_io.py
  requirements/env_omnisci.yml
Labels: OmniSci

#3468 DOCS-#3354: add note about Dask's approximate quantile
  docs/comparisons/dask.rst
Labels: Ready for review

#3493 FIX-#3447: Add attribute `api` in `modin.pandas`
  modin/pandas/__init__.py
  modin/pandas/test/test_rolling.py
Labels: Ready for review

#3465 FIX-#2588: read_feather: cast columns from Index to list
  modin/engines/base/io/column_stores/feather_dispatcher.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#3467 DOCS-#3367: read_hdf: change Y -> D in io_supported.rst
  docs/supported_apis/io_supported.rst
Labels: Ready for review

#3469 FIX-#3251: unpin mindsdb_sql
  .github/workflows/ci.yml
  setup.py
Labels: Ready for review

#3476 FIX-#3475: pandas.read_gbq: remove deprecated parameters
  modin/engines/base/io/io.py
Labels: Ready for review

#3495 FIX-#3424: Switch omnisci engine to native in dockerfile and examples
  examples/docker/modin-omnisci/Dockerfile
  examples/docker/modin-omnisci/census-omnisci.py
  examples/docker/modin-omnisci/nyc-taxi-omnisci.py
  examples/docker/modin-omnisci/plasticc-omnisci.py
Labels: Ready for review
