Repository modin-project/modin, pull requests merged in 2022-01, with the labels that each got.

#3882 REFACTOR-#3881: remove unused '_read_parquet_columns' function
  modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
Labels: Ready for review

#3874 DOCS-#3873: fix 'more than one target found for cross-reference DataFrame' warning
  docs/flow/modin/experimental/pandas.rst
Labels: Ready for review

#3797 DOCS-#3766: update 'read_csv_glob' dispatcher, parser and docstring
  modin/core/io/text/csv_glob_dispatcher.py
  modin/core/storage_formats/pandas/parsers.py
  modin/experimental/pandas/io.py
  modin/experimental/pandas/test/test_io_exp.py
Labels: Ready for review, External, Backport :back:

#3769 REFACTOR-#3768: change 'compute_chunksize' signature
  modin/config/envvars.py
  modin/core/dataframe/pandas/partitioning/partition_manager.py
  modin/core/io/column_stores/column_store_dispatcher.py
  modin/core/io/text/text_file_dispatcher.py
  modin/core/storage_formats/pandas/utils.py
  modin/core/storage_formats/pyarrow/parsers.py
Labels: Ready for review

#3870 TEST-#3869: add build-docs check in CI
  .github/workflows/ci.yml
Labels: Ready for review

#3746 FIX-#3219: delegate 'apply' result type inference to backend
  modin/core/storage_formats/base/query_compiler.py
  modin/core/storage_formats/pandas/query_compiler.py
  modin/pandas/dataframe.py
  modin/pandas/test/dataframe/test_udf.py
  modin/pandas/test/utils.py
Labels: Ready for review

#3779 DOCS-#3778: Improve documentation for Modin vs. Dask
  docs/getting_started/dask.rst
  docs/getting_started/index.rst
  docs/getting_started/modin_vs_dask_vs_koalas.rst
  docs/img/api_coverage_comparison.svg
  docs/img/performance-all-supported.svg
  docs/img/performance-not-all-supported.svg
  docs/modin_vs_dask.md
  docs/supported_apis/utilities_supported.rst
Labels: documentation 📜

#3373 FIX-#3197: do not pass lambdas to the backend in GroupBy
  modin/core/dataframe/algebra/default2pandas/groupby.py
  modin/core/dataframe/algebra/groupby.py
  modin/core/storage_formats/base/doc_utils.py
  modin/core/storage_formats/base/query_compiler.py
  modin/core/storage_formats/pandas/query_compiler.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/test/test_dataframe.py
  modin/experimental/core/storage_formats/omnisci/query_compiler.py
  modin/pandas/groupby.py
Labels: Ready for review

#4015 Exclude "scripts" from setup package
  setup.py
Labels: Backport :back:

#3986 FIX-#3985: Update pyarrow in environment files
  environment-dev.yml
  requirements-dev.txt
  requirements/env_omnisci.yml
  requirements/requirements-no-engine.yml
  setup.py
Labels: Backport :back:

#3658 FEAT-#3709: Update Modin tutorials
  examples/tutorial/requirements.txt
  examples/tutorial/tutorial_notebooks/cluster/exercise_4.ipynb
  examples/tutorial/tutorial_notebooks/cluster/exercise_5.ipynb
  examples/tutorial/tutorial_notebooks/cluster/exercise_6.ipynb
  examples/tutorial/tutorial_notebooks/introduction/exercise_2.ipynb
  examples/tutorial/tutorial_notebooks/introduction/exercise_3.ipynb
  examples/tutorial/tutorial_notebooks/introduction/exercise_4.ipynb
Labels: documentation 📜

#4007 Implement "modin.pandas.show_versions()" and "python -m modin --versions"
  modin/__main__.py
  modin/config/envvars.py
  modin/pandas/__init__.py
  modin/test/test_utils.py
  modin/utils.py
  setup.cfg
Labels: Backport :back:

#4037 FIX-#4017: Fix OmniSci engine enabling for IO functions
  .github/workflows/ci.yml
  modin/experimental/core/execution/native/implementations/omnisci_on_native/test/test_dataframe.py
  modin/pandas/io.py
Labels: Ready for review

#3946 FIX-#3945: bump omnisci version to 5.10.1
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/partitioning/partition_manager.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/test/utils.py
  requirements/env_omnisci.yml
Labels: Ready for review, OmniSci

#4083 DOCS-#4082: Add `pdf`/`epub`/`htmlzip` formats for doc builds
  .readthedocs.yaml
  docs/release_notes/release_notes-0.14.0.rst
Labels: Ready for review

#4114 FIX-#4113, FIX-#4116, FIX-#4115: Apply new `black` formatting, fix pydocstyle check and readthedocs build
  docs/release_notes/release_notes-0.14.0.rst
  docs/requirements-doc.txt
  modin/core/storage_formats/pandas/parsers.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py
  modin/pandas/test/dataframe/test_binary.py
  modin/pandas/test/dataframe/test_join_sort.py
  modin/pandas/test/dataframe/test_reduce.py
  modin/pandas/test/test_concat.py
  modin/pandas/test/test_groupby.py
  modin/pandas/test/test_series.py
  modin/pandas/test/utils.py
  modin/test/test_envvar_npartitions.py
  modin/test/test_partition_api.py
  scripts/doc_checker.py
Labels: Ready for review, P0
