Repository modin-project/modin, pull requests merged in 2022-02, with the labels that each got.

#3419 FIX-#3417: Fix read_csv with `skiprows` and `header` parameters
  docs/release_notes/release_notes-0.14.0.rst
  modin/core/io/text/fwf_dispatcher.py
  modin/core/io/text/text_file_dispatcher.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#3226 TEST-#3227: use codecov github action instead of bash form
  .github/workflows/ci.yml
  .github/workflows/push.yml
  docs/release_notes/release_notes-0.14.0.rst
Labels: Ready for review

#4163 FIX-#4162: Use `skipif` instead of `skip` for compatibility with pytest 7.0
  docs/release_notes/release_notes-0.14.0.rst
  modin/pandas/test/test_io.py
Labels: P0

#4152 DOCS-#4151: Add info in troubleshooting page related to Dask engine usage
  docs/getting_started/troubleshooting.rst
  docs/release_notes/release_notes-0.14.0.rst
Labels: Ready for review

#4170 FIX-#4115: Unpin `pip` in readthedocs deps list
  docs/release_notes/release_notes-0.14.0.rst
  docs/requirements-doc.txt
Labels: Ready for review

#3996 REFACTOR-#3997: remove code duplication for `broadcast_apply` method
  docs/release_notes/release_notes-0.14.0.rst
  modin/core/dataframe/pandas/partitioning/partition_manager.py
  modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
Labels: Ready for review

#4156 TEST-#4153: Fix condition of running lint-commit and set of CI triggers
  .github/workflows/ci-required.yml
  .github/workflows/ci.yml
  docs/release_notes/release_notes-0.14.0.rst
Labels: Ready for review

#4145 TEST-#3938: Test tutorial notebooks in CI
  .github/workflows/ci-notebooks.yml
  docs/release_notes/release_notes-0.14.0.rst
  examples/tutorial/tutorial_notebooks/introduction/exercise_3.ipynb
  examples/tutorial/tutorial_notebooks/test/test_notebooks.py
Labels: Ready for review

#4218 TEST-#4217: Pin `Dask<2022.2.0` as a temporary fix of CI
  docs/release_notes/release_notes-0.14.0.rst
  environment-dev.yml
  requirements-dev.txt
  setup.py
Labels: Ready for review

#4198 TEST-#3628: report coverage data for `test-internals` CI job
  .github/workflows/ci.yml
  .github/workflows/push.yml
  docs/release_notes/release_notes-0.14.0.rst
Labels: Ready for review

#4230 REFACTOR-#4229: remove unused `dask_client` global variable in `modin\pandas\__init__.py`
  docs/release_notes/release_notes-0.14.0.rst
  modin/pandas/__init__.py
  modin/pandas/test/test_api.py
Labels: Ready for review

#3995 REFACTOR-#3994: remove code duplication for `get_indices` function
  docs/release_notes/release_notes-0.14.0.rst
  modin/core/dataframe/pandas/partitioning/partition_manager.py
  modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
Labels: Ready for review

#4246 FEAT-#4245: Define base interface for dataframe exchange protocol
  .github/workflows/ci.yml
  .github/workflows/push.yml
  docs/release_notes/release_notes-0.14.0.rst
  modin/conftest.py
  modin/core/dataframe/base/exchange/__init__.py
  modin/core/dataframe/base/exchange/dataframe_protocol/__init__.py
  modin/core/dataframe/base/exchange/dataframe_protocol/dataframe.py
  modin/core/dataframe/base/exchange/dataframe_protocol/utils.py
  modin/core/execution/dispatching/factories/dispatcher.py
  modin/core/execution/dispatching/factories/factories.py
  modin/core/io/io.py
  modin/core/storage_formats/base/query_compiler.py
  modin/core/storage_formats/pandas/query_compiler.py
  modin/experimental/core/storage_formats/omnisci/query_compiler.py
  modin/pandas/dataframe.py
  modin/pandas/utils.py
  modin/test/exchange/__init__.py
  modin/test/exchange/dataframe_protocol/__init__.py
  modin/test/exchange/dataframe_protocol/base/__init__.py
  modin/test/exchange/dataframe_protocol/base/test_sanity.py
  modin/test/exchange/dataframe_protocol/base/test_utils.py
  modin/test/test_executions_api.py
Labels: Ready for review

#3868 REFACTOR-#4251: define public interfaces in `modin.core.execution.ray` module
  docs/flow/modin/core/execution/ray/generic.rst
  docs/flow/modin/core/execution/ray/implementations/cudf_on_ray/dataframe.rst
  docs/flow/modin/core/execution/ray/implementations/cudf_on_ray/io.rst
  docs/flow/modin/core/execution/ray/implementations/cudf_on_ray/partitioning/partition.rst
  docs/flow/modin/core/execution/ray/implementations/cudf_on_ray/partitioning/partition_manager.rst
  docs/flow/modin/core/execution/ray/implementations/pandas_on_ray/dataframe.rst
  docs/flow/modin/core/execution/ray/implementations/pandas_on_ray/index.rst
  docs/flow/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.rst
  docs/flow/modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.rst
  modin/core/execution/ray/common/__init__.py
  modin/core/execution/ray/common/task_wrapper.py
  modin/core/execution/ray/common/utils.py
  modin/core/execution/ray/generic/modin_aqp.py
  modin/core/execution/ray/generic/partitioning/__init__.py
  modin/core/execution/ray/implementations/cudf_on_ray/dataframe/__init__.py
  modin/core/execution/ray/implementations/cudf_on_ray/dataframe/dataframe.py
  modin/core/execution/ray/implementations/cudf_on_ray/io/__init__.py
  modin/core/execution/ray/implementations/cudf_on_ray/io/io.py
  modin/core/execution/ray/implementations/cudf_on_ray/io/text/__init__.py
  modin/core/execution/ray/implementations/cudf_on_ray/partitioning/__init__.py
  modin/core/execution/ray/implementations/cudf_on_ray/partitioning/partition_manager.py
  modin/core/execution/ray/implementations/pandas_on_ray/dataframe/__init__.py
  modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/__init__.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
  modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/io/io.py
  modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/partitioning/partition.py
  modin/experimental/core/execution/ray/implementations/pyarrow_on_ray/partitioning/partition_manager.py
  modin/pandas/__init__.py
Labels: Ready for review

#4231 FIX-#4221: add `wait` method for `PandasOnRayDataframeColumnPartition` class
  .github/workflows/ci.yml
  asv_bench/benchmarks/utils/common.py
  docs/release_notes/release_notes-0.14.0.rst
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
Labels: P1, Ready for review
