Repository modin-project/modin, pull requests merged in 2022-10, with the labels that each got.

#5069 TEST-#5068: add binary op benchmark for Series
  asv_bench/benchmarks/benchmarks.py
  asv_bench/benchmarks/utils/data_shapes.py
  docs/release_notes/release_notes-0.16.0.rst
Labels: Ready for review

#5063 TEST-#5102: Add HDK benchmarks to github workflows
  .github/workflows/ci.yml
  examples/data/census_1k.csv
  examples/data/nyc-taxi_1k.csv
  examples/data/plasticc_test_set_1k.csv
  examples/data/plasticc_test_set_metadata_1k.csv
  examples/data/plasticc_training_set_1k.csv
  examples/data/plasticc_training_set_metadata_1k.csv
  examples/docker/modin-hdk/census-hdk.py
  examples/docker/modin-hdk/nyc-taxi-hdk.py
  examples/docker/modin-hdk/plasticc-hdk.py
  examples/docker/modin-hdk/utils.py
  requirements/env_hdk.yml
Labels: Testing 📈

#5031 PERF-#5087: use cache for widths/lengths/index/columns if possible
  modin/core/dataframe/pandas/dataframe/dataframe.py
Labels: Ready for review

#5093 REFACTOR-#5092: Fix future warning for `set_axis` function
  modin/_compat/pandas_api/latest/base.py
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/core/storage_formats/pandas/query_compiler.py
  modin/pandas/base.py
  modin/pandas/test/dataframe/test_join_sort.py
  modin/pandas/test/dataframe/test_map_metadata.py
Labels: Ready for review, Backport :back:

#5021 BENCH: add some cases for `join` and `merge` ops from pandas
  asv_bench/benchmarks/benchmarks.py
  asv_bench/benchmarks/utils/__init__.py
  asv_bench/benchmarks/utils/common.py
  asv_bench/benchmarks/utils/data_shapes.py
Labels: Ready for review
