Repository modin-project/modin, pull requests merged in 2022-03, with the labels that each got.

#4256 FIX-#3368: support unsigned integers in OmniSci backend
  docs/release_notes/release_notes-0.14.0.rst
  modin/experimental/core/execution/native/implementations/omnisci_on_native/omnisci_worker.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/test/test_dataframe.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/test/utils.py
Labels: Ready for review, OmniSci

#4203 TEST-#4201: Add read_parquet, explode, tail, and various arithmetic t…
  asv_bench/benchmarks/benchmarks.py
  asv_bench/benchmarks/io/parquet.py
  asv_bench/benchmarks/utils/__init__.py
  asv_bench/benchmarks/utils/common.py
  asv_bench/benchmarks/utils/data_shapes.py
  docs/release_notes/release_notes-0.14.0.rst
Labels: Benchmarking 🏁

#4309 FIX-#4308: Add proper error handling in df.set_index
  docs/release_notes/release_notes-0.14.0.rst
  modin/pandas/dataframe.py
  modin/pandas/test/dataframe/test_indexing.py
Labels: Backport :back:

#3441 FEAT-#3603: add experimental `read_custom_text` function that can read custom line-by-line text files
  docs/release_notes/release_notes-0.14.0.rst
  modin/core/execution/dispatching/factories/dispatcher.py
  modin/core/execution/dispatching/factories/factories.py
  modin/core/io/__init__.py
  modin/core/io/text/custom_text_dispatcher.py
  modin/core/storage_formats/pandas/parsers.py
  modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/experimental/pandas/__init__.py
  modin/experimental/pandas/io.py
  modin/experimental/pandas/test/test_io_exp.py
Labels: Ready for review

#3854 REFACTOR-#3853: interacting with Dask interface through 'DaskWrapper' class
  docs/flow/modin/core/execution/dask/implementations/pandas_on_dask/index.rst
  docs/img/pandas_on_dask_data_ingress.svg
  docs/release_notes/release_notes-0.14.0.rst
  modin/core/execution/dask/common/engine_wrapper.py
  modin/core/execution/dask/implementations/pandas_on_dask/dataframe/dataframe.py
  modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
  modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
  modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
  modin/core/execution/dask/implementations/pandas_on_dask/partitioning/virtual_partition.py
  modin/core/execution/ray/common/task_wrapper.py
  modin/core/execution/ray/implementations/cudf_on_ray/io/text/csv_dispatcher.py
  modin/core/io/column_stores/column_store_dispatcher.py
  modin/core/io/file_dispatcher.py
  modin/core/io/pickle/pickle_dispatcher.py
  modin/core/io/sql/sql_dispatcher.py
  modin/core/io/text/csv_glob_dispatcher.py
  modin/core/io/text/excel_dispatcher.py
  modin/core/io/text/json_dispatcher.py
  modin/core/io/text/text_file_dispatcher.py
  modin/test/test_partition_api.py
Labels: Ready for review

#4341 DOCS-#4339: Reformat I/O functions docstrings
  docs/release_notes/release_notes-0.14.0.rst
  modin/pandas/io.py
Labels: Ready for review

#4269 FEAT-#4244: Implement dataframe exchange protocol for OmniSci
  .github/workflows/ci.yml
  .github/workflows/push.yml
  docs/release_notes/release_notes-0.14.0.rst
  modin/core/dataframe/base/exchange/dataframe_protocol/utils.py
  modin/core/dataframe/pandas/exchange/dataframe_protocol/from_dataframe.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/dataframe/dataframe.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/__init__.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/dataframe_protocol/__init__.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/dataframe_protocol/buffer.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/dataframe_protocol/column.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/dataframe_protocol/dataframe.py
  modin/experimental/core/execution/native/implementations/omnisci_on_native/exchange/dataframe_protocol/utils.py
  modin/experimental/core/storage_formats/omnisci/query_compiler.py
  modin/test/exchange/dataframe_protocol/omnisci/__init__.py
  modin/test/exchange/dataframe_protocol/omnisci/test_protocol.py
  modin/test/exchange/dataframe_protocol/omnisci/utils.py
Labels: Ready for review, OmniSci

#4338 DOCS-#4336: Reformat general utilities docstrings
  docs/release_notes/release_notes-0.14.0.rst
  modin/pandas/general.py
Labels: Ready for review
