Repository modin-project/modin, pull requests merged in 2023-05, with the labels that each got.

#6145 FEAT-#6144: Stop defaulting at API layer for a bunch of methods
  modin/core/dataframe/algebra/default2pandas/default.py
  modin/core/storage_formats/base/query_compiler.py
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/series.py
Labels: ponder

#6178 FIX-#6094: pin 'urllib3<2' for pip command in 'test-ray-master' job
  .github/workflows/push-to-master.yml
Labels: Ready for review, P0

#6033 TEST-#6030: test the function parameters of `Series.str` accessor for pandas equivalence
  modin/pandas/test/test_api.py
Labels: Ready for review

#6177 DOCS-#6078: correct default values for MODIN_CPUS and MODIN_NPARTITIONS
  modin/config/__main__.py
Labels: Ready for review

#6059 TEST-#6198: add `pragma: no cover` for unidist and ray utils that used in remote context
  modin/core/execution/ray/common/utils.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
  modin/core/execution/unidist/common/utils.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
Labels: Ready for review

#6061 FIX-#6196: Align `Series.cat` signatures with pandas
  modin/pandas/series_utils.py
  modin/pandas/test/test_api.py
Labels: Ready for review

#6197 TEST-#6031: test the function parameters of `Series.dt` accessor for pandas equivalence
  modin/pandas/test/test_api.py
Labels: Ready for review

#6200 FIX-#6199: make sure `read_html` return a list of DataFrames
  modin/core/io/io.py
  modin/pandas/io.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#6202 FIX-#6201: align groupby objects signatures with pandas
  modin/pandas/groupby.py
  modin/pandas/test/test_api.py
Labels: Ready for review
