Repository modin-project/modin, pull requests merged in 2023-01, with the labels that each got.

#5513 FIX-#5514: pin sphinx<6.0.0
  docs/requirements-doc.txt
Labels: Ready for review, P0

#5516 FIX-#4186: Fix `__repr__` of Modin categorical Series
  modin/pandas/series.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#5515 FIX-#2493: Defaults to pandas for read_csv if `lineterminator!=None`
  modin/core/io/text/text_file_dispatcher.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#5512 FIX-#2508: Defaults to pandas for read_csv if `dialect!=None`
  modin/core/io/text/text_file_dispatcher.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#5520 REFACTOR-#3883: Unify tests execution approach in the Github workflow files
  .github/workflows/ci-notebooks.yml
  .github/workflows/ci.yml
  .github/workflows/push-to-master.yml
  .github/workflows/push.yml
Labels: Ready for review

#5521 FIX-#2494: Defaults to pandas for read_csv if `escapechar!=None`
  modin/core/io/text/text_file_dispatcher.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#5493 FIX-#5492: Fix `Series.values` when `Series.dtype==ExtensionDtype`
  modin/pandas/base.py
  modin/pandas/series.py
  modin/pandas/test/test_series.py
  modin/pandas/test/utils.py
Labels: P1, Ready for review

#5480 DOCS-#3803: Update "building modin from source" docs
  docs/getting_started/installation.rst
Labels: Ready for review

#5522 FIX-#2320: Raise exceptions in read_csv in some cases with `skipfooter!=0`
  modin/core/io/text/text_file_dispatcher.py
  modin/experimental/core/execution/native/implementations/hdk_on_native/io/io.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#5502 FIX-#1227: Avoid `RecursionError` for `__int__` and `__float__`
  modin/pandas/series.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#5534 REFACTOR-#5535: remove duplication for `columnarize` method
  modin/core/storage_formats/pandas/query_compiler.py
Labels: Ready for review

#5538 FIX-#5537: disable empty-groupby handling logic in experimental mode
  .github/workflows/ci.yml
  modin/pandas/groupby.py
Labels: Ready for review

#5544 PERF-#5550: Don't trigger axes computation in `to_pandas` function
  modin/core/dataframe/pandas/dataframe/dataframe.py
Labels: Ready for review

#5541 PERF-#5549: copy dtypes for `__invert__` op
  modin/core/storage_formats/pandas/query_compiler.py
Labels: Ready for review

#5543 PERF-#5551: Preserve index and columns on `_repartition`
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/core/execution/python/implementations/pandas_on_python/partitioning/partition.py
  modin/core/storage_formats/base/query_compiler.py
Labels: Ready for review

#5579 FIX-#5581: Don't use deprecated `inplace` parameter for `set_axis` function
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/pandas/base.py
Labels: Ready for review

#5548 PERF-#5573: Don't trigger axes computation in `columnarize` function
  modin/core/storage_formats/base/query_compiler.py
  modin/core/storage_formats/pandas/query_compiler.py
  modin/experimental/core/storage_formats/pyarrow/query_compiler.py
Labels: Ready for review

#5546 PERF-#5557: Don't trigger axes computation in `pivot_table`
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/core/storage_formats/pandas/query_compiler.py
Labels: Ready for review

#5508 FIX-#3305: Fix `read_excel` when `usecols` and `index_cols` parameters are provided
  modin/core/io/text/excel_dispatcher.py
  modin/core/storage_formats/pandas/parsers.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#5593 FIX-#5597: Pin sqlalchemy<1.4.46 as pandas does to fix CI
  environment-dev.yml
  requirements-dev.txt
  requirements/env_hdk.yml
  requirements/env_unidist.yml
  requirements/requirements-no-engine.yml
Labels: Ready for review
