Repository modin-project/modin, pull requests merged in 2023-03, with the labels that each got.

#5717 REFACTOR-#5718: add `columns` parameter for `get_dtypes` function
  modin/core/io/text/csv_glob_dispatcher.py
  modin/core/io/text/excel_dispatcher.py
  modin/core/io/text/json_dispatcher.py
  modin/core/io/text/text_file_dispatcher.py
  modin/core/storage_formats/pandas/parsers.py
Labels: Ready for review

#5632 PERF-#5247: Decrease memory consumption for MultiIndex
  modin/core/storage_formats/pandas/utils.py
Labels: Ready for review

#5143 FEAT-#5147: implement xs
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/series.py
  modin/pandas/test/dataframe/test_indexing.py
Labels: Ready for review

#5701 REFACTOR-#5703: align `DaskWrapper.deploy` behavior with others
  modin/core/execution/dask/common/engine_wrapper.py
  modin/core/execution/ray/common/engine_wrapper.py
  modin/core/execution/unidist/common/engine_wrapper.py
Labels: Ready for review

#5745 TEST-#5747: Synchronize jobs between push.yml and ci.yml that are used to measure test coverage
  .github/workflows/ci.yml
  .github/workflows/fuzzydata-test.yml
  .github/workflows/push.yml
Labels: Ready for review

#5679 PERF-#5670: create `self._identity` in partitions only for "debug" logging level
  modin/core/dataframe/pandas/partitioning/partition.py
  modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
Labels: Ready for review

#5678 PERF-#5674: reduce data transferring in `_launch_tasks` function
  modin/core/execution/dask/common/engine_wrapper.py
  modin/core/io/text/text_file_dispatcher.py
  modin/core/storage_formats/pandas/parsers.py
Labels: Ready for review

#5408 REFACTOR-#5414: Move `partition.get` into base class
  modin/core/dataframe/pandas/partitioning/partition.py
  modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition.py
Labels: Ready for review

#5785 REFACTOR-#5786: align logging of Dask partitions with other executions
  modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition.py
Labels: Ready for review

#5407 REFACTOR-#5417: fix FutureWarning: the `mangle_dupe_cols` keyword is deprecated
  modin/experimental/core/execution/native/implementations/hdk_on_native/io/io.py
  modin/experimental/pandas/io.py
Labels: Ready for review

#5789 TEST-#5790: add ASV configs for Dask and Unidist
  asv_bench/asv.conf.dask.json
  asv_bench/asv.conf.unidist.json
  asv_bench/benchmarks/utils/compatibility.py
Labels: Ready for review

#5801 TEST-#5802: update some actions in CI
  .github/workflows/ci-notebooks.yml
  .github/workflows/ci.yml
  .github/workflows/fuzzydata-test.yml
  .github/workflows/push-to-master.yml
Labels: Ready for review

#5780 PERF-#5778: Avoid extra materialization at range-based reshuffling
  modin/core/dataframe/pandas/partitioning/partition_manager.py
Labels: partitions reshuffling 🔀

#5782 TEST-#2544: delay `codecov` notifications until all reports have been sent
  .github/workflows/ci.yml
  .github/workflows/upload-coverage/action.yml
  setup.cfg
Labels: Ready for review

#5804 FIX-#5776: fix IndexError when concatenating dict of series along columns
  modin/pandas/general.py
  modin/pandas/test/test_concat.py
Labels: Ready for review

#4228 FIX-#4227: Calling `FactoryDispatcher.get_factory` also initializes the engine
  modin/core/execution/dispatching/factories/dispatcher.py
  modin/core/execution/dispatching/factories/test/test_dispatcher.py
  modin/experimental/pandas/io.py
  modin/pandas/io.py
Labels: Ready for review

#5783 FIX-#5781: Fix sort in descending order for columns with highly dense values
  modin/core/dataframe/pandas/dataframe/utils.py
  modin/pandas/test/dataframe/test_join_sort.py
  modin/test/storage_formats/pandas/test_internals.py
Labels: partitions reshuffling 🔀

#5779 PERF-#5777: Filter out empty bins at range-based reshuffling
  modin/core/dataframe/pandas/partitioning/partition_manager.py
Labels: partitions reshuffling 🔀

#5784 FIX-#5309: series iloc/loc raises IndexingError if a key is too long
  modin/pandas/indexing.py
  modin/pandas/test/dataframe/test_indexing.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#5854 TEST-#0000: fix typo: `read_stata kwargs` -> `read_sas kwargs`
  modin/pandas/test/test_io.py
Labels: Ready for review

#5853 DOCS-#5852: Add mention of `read_custom_text` experimental api in docs
  docs/flow/modin/experimental/pandas.rst
  docs/usage_guide/advanced_usage/index.rst
Labels: Ready for review

#5861 FIX-#5862: fix Inline strong start-string without end-string for read_custom_text
  modin/experimental/pandas/io.py
Labels: P0

#5855 REFACTOR-#5863: remove `Engine.subscribe(_update_engine)` in DataFrame/Series constructors
  modin/pandas/dataframe.py
  modin/pandas/series.py
Labels: Ready for review

#5848 FIX-#5849: add `Series.dt.day_of_week/day_of_year/isocalendar/asfreq` methods
  modin/core/storage_formats/base/query_compiler.py
  modin/core/storage_formats/pandas/query_compiler.py
  modin/pandas/series_utils.py
  modin/pandas/test/test_api.py
  modin/pandas/test/test_series.py
Labels: P0

#5864 REFACTOR-#5830: rename experimental dispatchers and parsers
  modin/core/io/__init__.py
  modin/core/io/pickle/pickle_dispatcher.py
  modin/core/io/text/custom_text_dispatcher.py
  modin/core/storage_formats/pandas/parsers.py
  modin/experimental/core/execution/dask/implementations/pandas_on_dask/io/io.py
  modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/experimental/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
  modin/experimental/core/io/__init__.py
  modin/experimental/core/io/sql/sql_dispatcher.py
Labels: Ready for review

#5877 TEST-#5878: exclude modin/experimental/batch/test/ folder from computing coverage
  setup.cfg
Labels: Ready for review

#5873 REFACTOR-#5875: use default implementations for dt methods from the base query compiler
  modin/core/storage_formats/pandas/query_compiler.py
Labels: Ready for review

#5881 TEST-#4261: test rolling with axis=1, win_type=, and center=True
  modin/pandas/test/test_rolling.py
Labels: Ready for review

#5876 FEAT-#4624: add `to_parquet` parallel implementation for Dask
  docs/supported_apis/dataframe_supported.rst
  modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
Labels: Ready for review

#5882 REFACTOR-#2863: remove `other_name` from broadcast_apply
  modin/core/dataframe/pandas/partitioning/partition_manager.py
Labels: Ready for review

#5879 FEAT-#5880: add `to_sql` parallel implementation for Dask
  modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
  modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
Labels: Ready for review

#5895 FIX-#5618: don't ignore 'errors' parameter for astype
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/core/storage_formats/pandas/query_compiler.py
  modin/pandas/test/dataframe/test_map_metadata.py
Labels: Ready for review

#5883 FIX-#2850: use modin.pandas.Series instead of pandas.Series for `where` func
  modin/core/storage_formats/pandas/query_compiler.py
  modin/pandas/dataframe.py
  modin/pandas/test/dataframe/test_join_sort.py
  modin/pandas/test/test_series.py
Labels: Ready for review

#5677 PERF-#5675: make index calculation for `read_csv` function lazy; introduce `ModinIndex`
  .github/workflows/ci-notebooks.yml
  modin/core/dataframe/algebra/binary.py
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/core/dataframe/pandas/metadata/__init__.py
  modin/core/dataframe/pandas/metadata/index.py
  modin/core/io/text/text_file_dispatcher.py
  modin/core/storage_formats/base/query_compiler.py
  modin/core/storage_formats/pandas/query_compiler.py
  modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
  modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/utils.py
  modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
  modin/experimental/core/storage_formats/hdk/query_compiler.py
  modin/pandas/test/dataframe/test_indexing.py
  modin/pandas/test/dataframe/test_join_sort.py
  modin/pandas/test/test_groupby.py
Labels: Ready for review

#5907 REFACTOR-#5908: remove unused parameters from `run_exec_plan`
  modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
  modin/experimental/core/execution/native/implementations/hdk_on_native/partitioning/partition_manager.py
  modin/experimental/core/execution/native/implementations/hdk_on_native/test/utils.py
Labels: Ready for review

#5909 REFACTOR-#5910: remove `_dtypes_for_cols` internal function as unused
  modin/experimental/core/execution/native/implementations/hdk_on_native/dataframe/dataframe.py
Labels: Ready for review

#5872 REFACTOR-#5874: move `lazy_metadata_decorator` into `utils.py`
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/core/dataframe/pandas/dataframe/utils.py
Labels: Ready for review

#5899 FEAT-#5901: add `read_fwf` parallel implementation for Dask
  docs/supported_apis/io_supported.rst
  modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
Labels: Ready for review

#5866 FIX-#5454: add missed methods for `SeriesGroupBy`, `DataFrameGroupBy` objects
  modin/pandas/groupby.py
  modin/pandas/test/test_api.py
  modin/pandas/test/test_groupby.py
Labels: Ready for review, P0

#5911 FIX-#5509: default to pandas for read_parquet if any additional kwargs are passed to the engine
  modin/core/io/column_stores/parquet_dispatcher.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#5860 FIX-#5767: cast `pathlib.Path` to str for `read_parquet`
  modin/core/io/column_stores/parquet_dispatcher.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#5915 FIX-#4635: allow pass modin functions to `apply`
  modin/pandas/dataframe.py
  modin/pandas/groupby.py
  modin/pandas/resample.py
  modin/pandas/series.py
  modin/pandas/test/dataframe/test_udf.py
  modin/pandas/utils.py
  modin/pandas/window.py
Labels: Ready for review
