Repository modin-project/modin, pull requests merged in 2023-04, with the labels that each got.

#5921 REFACTOR-#5922: let `upload-coverage` action fail if there is no `.coverage` file
  .github/workflows/upload-coverage/action.yml
Labels: Ready for review

#5920 REFACTOR-#5923: add `pragma: no cover` for functions that used in `apply_full_axis`
  modin/core/dataframe/pandas/dataframe/dataframe.py
  modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
  modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
  modin/core/storage_formats/pandas/query_compiler.py
  modin/experimental/batch/pipeline.py
  modin/experimental/core/execution/dask/implementations/pandas_on_dask/io/io.py
  modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/experimental/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
  modin/experimental/core/io/sql/utils.py
Labels: Ready for review

#5918 FIX-#5432: don't return None when `astype` used with `copy=False` parameter
  modin/pandas/base.py
  modin/pandas/dataframe.py
  modin/pandas/test/dataframe/test_map_metadata.py
Labels: Ready for review

#5847 FIX-#5829: fix ndarray assignment via loc
  modin/pandas/indexing.py
  modin/pandas/test/dataframe/test_indexing.py
Labels: Ready for review

#5919 FIX-#4924: fix read_excel when header is None
  modin/core/io/text/excel_dispatcher.py
  modin/pandas/test/test_io.py
Labels: Ready for review

#5942 FIX-#5941: TEST: The test test_io.py fails on HDK
  modin/pandas/test/test_io.py
Labels: P0

#5890 TEST-#5943: Rebalance tests between different CI jobs
  .github/workflows/ci.yml
Labels: Ready for review

#5898 REFACTOR-#5902: use `__make_read` for non experimental IO classes
  modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
  modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
Labels: Ready for review

#5939 FIX-#5203: don't raise `AttributeError: 'list' object has no attribute '_query_compiler'` in `join` op
  modin/pandas/dataframe.py
  modin/pandas/test/dataframe/test_join_sort.py
Labels: Ready for review

#5917 TEST-#5980: use `cancel-in-progress` only for PRs
  .github/workflows/ci-notebooks.yml
  .github/workflows/ci-required.yml
  .github/workflows/ci.yml
  .github/workflows/codeql.yml
  .github/workflows/fuzzydata-test.yml
  .github/workflows/push-to-master.yml
Labels: Ready for review, P0

#5954 REFACTOR-#5844: remove `inplace` kwarg from query compiler `clip` arguments
  modin/core/storage_formats/base/query_compiler.py
  modin/pandas/base.py
Labels: Ready for review

#5950 REFACTOR-#5951: remove code duplication for `to_pickle_distributed`
  modin/core/io/__init__.py
  modin/experimental/core/execution/dask/implementations/pandas_on_dask/io/io.py
  modin/experimental/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/experimental/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
  modin/experimental/core/io/__init__.py
  modin/experimental/core/io/pickle/__init__.py
  modin/experimental/core/io/pickle/pickle_dispatcher.py
Labels: Ready for review

#6007 TEST-#6010: add some more test directories into `setup.cfg` to omit for coverage
  setup.cfg
Labels: Ready for review

#6002 TEST-#6004: add more `# pragma: no cover` for io functions
  modin/core/execution/dask/implementations/pandas_on_dask/io/io.py
  modin/core/execution/ray/implementations/pandas_on_ray/io/io.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/io/io.py
Labels: Ready for review

#5945 FIX-#4828: allow `dict_apply_builder` use keyword argument `internal_indices`
  modin/core/storage_formats/pandas/query_compiler.py
  modin/pandas/test/dataframe/test_udf.py
Labels: Ready for review

#6023 FIX-#6022: move `_DEPLOY_AXIS_FUNC`, `_DEPLOY_SPLIT_FUNC`, `_DRAIN` into Ray/Unidist virtual partition
  .github/workflows/ci.yml
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/virtual_partition.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/virtual_partition.py
  modin/pandas/test/integrations/__init__.py
  modin/pandas/test/integrations/test_lazy_import.py
Labels: External

#6045 REFACTOR-#6044: remove code duplication for `get_objects_from_partitions`
  modin/core/dataframe/pandas/partitioning/partition_manager.py
  modin/core/execution/dask/implementations/pandas_on_dask/partitioning/partition_manager.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition_manager.py
Labels: Ready for review

#6008 TEST-#6009: use `tmp_path` fixture instead of `ensure_clean_dir` as pandas 2.0.0 does
  modin/conftest.py
  modin/experimental/pandas/test/test_io_exp.py
  modin/pandas/test/test_io.py
  modin/pandas/test/utils.py
Labels: Ready for review

#6047 REFACTOR-#6046: remove code duplication for `progress_bar_wrapper`
  modin/core/execution/modin_aqp.py
  modin/core/execution/ray/implementations/pandas_on_ray/partitioning/partition_manager.py
  modin/core/execution/unidist/implementations/pandas_on_unidist/partitioning/partition_manager.py
Labels: Ready for review
